use crate::config::{ButtonAction, DeviceProfile, REMOTE_BUTTONS, RemoteButton};
use crate::i18n::{Language, language, tr};
use std::error::Error;
use std::fmt;

pub const RC003_VERIFIED_BUTTON_KEYS: [(RemoteButton, &str); 11] = [
    (RemoteButton::Up, "up"),
    (RemoteButton::Left, "left"),
    (RemoteButton::Ok, "enter"),
    (RemoteButton::Right, "right"),
    (RemoteButton::Down, "down"),
    (RemoteButton::Back, "back"),
    (RemoteButton::VolumeUp, "volumeup"),
    (RemoteButton::Home, "home"),
    (RemoteButton::VolumeDown, "volumedown"),
    (RemoteButton::Menu, "compose"),
    (RemoteButton::Tv, "grave"),
];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeydPreview {
    pub config: String,
    pub notices: Vec<String>,
}

impl KeydPreview {
    pub fn ready_to_apply(&self) -> bool {
        self.notices.is_empty()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum KeydPreviewError {
    MissingStableDeviceId,
    UnsupportedDeviceId {
        vendor: u16,
        product: u16,
    },
    UnsupportedPttKey(String),
    MissingShortcut(RemoteButton),
    InvalidShortcut {
        button: RemoteButton,
        reason: String,
    },
}

impl fmt::Display for KeydPreviewError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingStableDeviceId => formatter.write_str(tr("The device profile has no stable VID/PID; device names and temporary eventN paths will not be used to generate keyd configuration", "设备 Profile 缺少稳定 VID/PID；不会用设备名称或临时 eventN 生成 keyd 配置")),
            Self::UnsupportedDeviceId { vendor, product } => write!(
                formatter,
                "{}", match language() { Language::English => format!("This key map supports only the verified RC003 2717:32b8; the profile specifies {vendor:04x}:{product:04x}"), Language::SimplifiedChinese => format!("当前键表只适用于已验证的 RC003 2717:32b8；Profile 中是 {vendor:04x}:{product:04x}") }
            ),
            Self::UnsupportedPttKey(key) => {
                match language() { Language::English => write!(formatter, "Only the fixed F20 PTT key is currently allowed; the profile specifies “{key}”"), Language::SimplifiedChinese => write!(formatter, "当前只允许固定 F20 PTT，Profile 中是“{key}”") }
            }
            Self::MissingShortcut(button) => {
                match language() { Language::English => write!(formatter, "No custom shortcut is set for “{}”", button_label(*button)), Language::SimplifiedChinese => write!(formatter, "“{}”尚未设置自定义快捷键", button_label(*button)) }
            }
            Self::InvalidShortcut { button, reason } => match language() { Language::English => write!(formatter, "The custom shortcut for “{}” is invalid: {reason}", button_label(*button)), Language::SimplifiedChinese => write!(formatter, "“{}”的自定义快捷键无效：{reason}", button_label(*button)) },
        }
    }
}

impl Error for KeydPreviewError {}

pub fn rc003_source_key(button: RemoteButton) -> Option<&'static str> {
    RC003_VERIFIED_BUTTON_KEYS
        .iter()
        .find_map(|(candidate, key)| (*candidate == button).then_some(*key))
}

pub fn render_rc003_keyd_preview(profile: &DeviceProfile) -> Result<KeydPreview, KeydPreviewError> {
    let vendor = profile
        .matcher
        .vendor_id
        .ok_or(KeydPreviewError::MissingStableDeviceId)?;
    let product = profile
        .matcher
        .product_id
        .ok_or(KeydPreviewError::MissingStableDeviceId)?;
    if (vendor, product) != (0x2717, 0x32b8) {
        return Err(KeydPreviewError::UnsupportedDeviceId { vendor, product });
    }
    if !profile.ptt_key.eq_ignore_ascii_case("f20") {
        return Err(KeydPreviewError::UnsupportedPttKey(profile.ptt_key.clone()));
    }

    let mut lines = vec![
        "# Generated by OmaVoice from the selected device Profile.".to_string(),
        "# RC003 mappings: validated before atomic installation.".to_string(),
        "[ids]".to_string(),
        format!("k:{vendor:04x}:{product:04x}"),
        String::new(),
        "[main]".to_string(),
        "f5 = f20".to_string(),
    ];
    let mut notices = Vec::new();

    for button in REMOTE_BUTTONS {
        let action = profile.button_action(button);
        let Some(source_key) = rc003_source_key(button) else {
            if button == RemoteButton::Power && action == ButtonAction::PassThrough {
                lines.push("# power unchanged (not captured by keyd)".to_string());
                continue;
            }
            lines.push(format!(
                "# {} omitted: physical key is not safely captured",
                button_id(button)
            ));
            notices.push(match language() {
                Language::English => format!(
                    "{} is not yet captured safely; the configuration cannot be applied",
                    button_label(button)
                ),
                Language::SimplifiedChinese => format!(
                    "{} 尚未安全捕获；配置不能进入应用阶段",
                    button_label(button)
                ),
            });
            continue;
        };

        match action_binding(profile, button, action)? {
            Some(binding) => lines.push(format!("{source_key} = {binding}")),
            None if action == ButtonAction::PassThrough => {
                lines.push(format!("# {source_key} unchanged ({})", button_id(button)))
            }
            None => {
                lines.push(format!(
                    "# {source_key} omitted: {} is not available through keyd alone",
                    action_id(action)
                ));
                notices.push(match language() { Language::English => format!("“{} → Show Desktop” has no verified Omarchy shortcut; Super+D currently opens the Display menu", button_label(button)), Language::SimplifiedChinese => format!("“{} → 显示桌面”没有经过验证的 Omarchy 快捷键；当前 Super+D 是 Display 菜单", button_label(button)) });
            }
        }
    }
    lines.push(String::new());

    Ok(KeydPreview {
        config: lines.join("\n"),
        notices,
    })
}

fn action_binding(
    profile: &DeviceProfile,
    button: RemoteButton,
    action: ButtonAction,
) -> Result<Option<String>, KeydPreviewError> {
    let binding = match action {
        ButtonAction::Disabled => Some("noop"),
        ButtonAction::PassThrough | ButtonAction::ShowDesktop => None,
        ButtonAction::Escape => Some("esc"),
        ButtonAction::Enter => Some("enter"),
        ButtonAction::Backspace => Some("backspace"),
        ButtonAction::ArrowUp => Some("up"),
        ButtonAction::ArrowDown => Some("down"),
        ButtonAction::ArrowLeft => Some("left"),
        ButtonAction::ArrowRight => Some("right"),
        ButtonAction::ContextMenu => Some("compose"),
        ButtonAction::AppSwitcher => Some("A-tab"),
        ButtonAction::VolumeUp => Some("volumeup"),
        ButtonAction::VolumeDown => Some("volumedown"),
        ButtonAction::VolumeMute => Some("mute"),
        ButtonAction::PlayPause => Some("playpause"),
        ButtonAction::CustomShortcut => {
            let shortcut = profile
                .button_shortcut(button)
                .ok_or(KeydPreviewError::MissingShortcut(button))?;
            return shortcut
                .keyd_binding()
                .map(Some)
                .map_err(|reason| KeydPreviewError::InvalidShortcut { button, reason });
        }
    };
    Ok(binding.map(str::to_string))
}

pub(crate) const fn button_id(button: RemoteButton) -> &'static str {
    match button {
        RemoteButton::Power => "power",
        RemoteButton::Up => "up",
        RemoteButton::Left => "left",
        RemoteButton::Ok => "ok",
        RemoteButton::Right => "right",
        RemoteButton::Down => "down",
        RemoteButton::Back => "back",
        RemoteButton::VolumeUp => "volume_up",
        RemoteButton::Home => "home",
        RemoteButton::VolumeDown => "volume_down",
        RemoteButton::Menu => "menu",
        RemoteButton::Tv => "tv",
    }
}

fn button_label(button: RemoteButton) -> &'static str {
    match button {
        RemoteButton::Power => tr("Power", "电源"),
        RemoteButton::Up => tr("Up", "上"),
        RemoteButton::Left => tr("Left", "左"),
        RemoteButton::Ok => tr("OK", "确定"),
        RemoteButton::Right => tr("Right", "右"),
        RemoteButton::Down => tr("Down", "下"),
        RemoteButton::Back => tr("Back", "返回"),
        RemoteButton::VolumeUp => tr("Volume +", "音量+"),
        RemoteButton::Home => tr("Home", "主页"),
        RemoteButton::VolumeDown => tr("Volume −", "音量−"),
        RemoteButton::Menu => tr("Menu", "菜单"),
        RemoteButton::Tv => "TV",
    }
}

const fn action_id(action: ButtonAction) -> &'static str {
    match action {
        ButtonAction::Disabled => "disabled",
        ButtonAction::PassThrough => "pass_through",
        ButtonAction::Escape => "escape",
        ButtonAction::Enter => "enter",
        ButtonAction::Backspace => "backspace",
        ButtonAction::ArrowUp => "arrow_up",
        ButtonAction::ArrowDown => "arrow_down",
        ButtonAction::ArrowLeft => "arrow_left",
        ButtonAction::ArrowRight => "arrow_right",
        ButtonAction::ShowDesktop => "show_desktop",
        ButtonAction::ContextMenu => "context_menu",
        ButtonAction::AppSwitcher => "app_switcher",
        ButtonAction::VolumeUp => "volume_up",
        ButtonAction::VolumeDown => "volume_down",
        ButtonAction::VolumeMute => "volume_mute",
        ButtonAction::PlayPause => "play_pause",
        ButtonAction::CustomShortcut => "custom_shortcut",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::KeyboardShortcut;

    #[test]
    fn rc003_source_keys_match_structured_physical_capture() {
        assert_eq!(RC003_VERIFIED_BUTTON_KEYS.len(), 11);
        assert_eq!(rc003_source_key(RemoteButton::Ok), Some("enter"));
        assert_eq!(rc003_source_key(RemoteButton::Back), Some("back"));
        assert_eq!(rc003_source_key(RemoteButton::Menu), Some("compose"));
        assert_eq!(rc003_source_key(RemoteButton::Tv), Some("grave"));
        assert_eq!(rc003_source_key(RemoteButton::VolumeUp), Some("volumeup"));
        assert_eq!(
            rc003_source_key(RemoteButton::VolumeDown),
            Some("volumedown")
        );
        assert_eq!(rc003_source_key(RemoteButton::Power), None);
    }

    #[test]
    fn preview_uses_stable_device_id_and_keeps_mic_fixed() {
        let preview = render_rc003_keyd_preview(&DeviceProfile::default()).unwrap();

        assert!(preview.config.contains("[ids]\nk:2717:32b8"));
        assert!(preview.config.contains("[main]\nf5 = f20"));
        assert!(preview.config.contains("volumeup = volumeup"));
        assert!(preview.config.contains("volumedown = volumedown"));
        assert!(preview.config.contains("compose = compose"));
        assert!(!preview.config.contains("compose = menu"));
        assert!(!preview.config.contains("/dev/input/"));
        assert!(!preview.config.contains("小米蓝牙语音遥控器"));
        assert!(!preview.ready_to_apply());
        assert_eq!(preview.notices.len(), 2);
    }

    #[test]
    fn every_supported_action_renders_through_the_same_keyd_pipeline() {
        let mut profile = DeviceProfile::default();
        profile
            .button_mappings
            .insert(RemoteButton::Power, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Home, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Back, ButtonAction::Disabled);
        profile
            .button_mappings
            .insert(RemoteButton::Menu, ButtonAction::AppSwitcher);
        profile
            .button_mappings
            .insert(RemoteButton::Tv, ButtonAction::PlayPause);

        let preview = render_rc003_keyd_preview(&profile).unwrap();

        assert!(preview.ready_to_apply());
        assert!(preview.notices.is_empty());
        assert!(
            preview
                .config
                .contains("# power unchanged (not captured by keyd)")
        );
        assert!(preview.config.contains("back = noop"));
        assert!(preview.config.contains("# home unchanged"));
        assert!(preview.config.contains("compose = A-tab"));
        assert!(preview.config.contains("grave = playpause"));
    }

    #[test]
    fn structured_custom_shortcut_renders_without_keyd_command_text() {
        let mut profile = DeviceProfile::default();
        profile
            .button_mappings
            .insert(RemoteButton::Power, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Home, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Tv, ButtonAction::CustomShortcut);
        profile.button_shortcuts.insert(
            RemoteButton::Tv,
            KeyboardShortcut::from_input(true, false, true, true, "P").unwrap(),
        );

        let preview = render_rc003_keyd_preview(&profile).unwrap();

        assert!(preview.ready_to_apply());
        assert!(preview.config.contains("grave = C-S-M-p"));
        assert!(!preview.config.contains("macro("));
        assert!(!preview.config.contains("command("));
    }

    #[test]
    fn custom_action_without_a_shortcut_blocks_preview() {
        let mut profile = DeviceProfile::default();
        profile
            .button_mappings
            .insert(RemoteButton::Tv, ButtonAction::CustomShortcut);

        assert_eq!(
            render_rc003_keyd_preview(&profile),
            Err(KeydPreviewError::MissingShortcut(RemoteButton::Tv))
        );
    }

    #[test]
    fn uncaptured_power_blocks_every_action_except_pass_through() {
        for action in [
            ButtonAction::Disabled,
            ButtonAction::Escape,
            ButtonAction::Enter,
            ButtonAction::ShowDesktop,
            ButtonAction::PlayPause,
        ] {
            let mut profile = DeviceProfile::default();
            profile.button_mappings.insert(RemoteButton::Power, action);
            profile
                .button_mappings
                .insert(RemoteButton::Home, ButtonAction::PassThrough);

            let preview = render_rc003_keyd_preview(&profile).unwrap();

            assert!(!preview.ready_to_apply(), "Power action {action:?}");
            assert_eq!(preview.notices.len(), 1, "Power action {action:?}");
            assert!(preview.config.contains("# power omitted"));
        }
    }

    #[test]
    fn preview_rejects_transient_identity_or_non_fixed_ptt() {
        let mut profile = DeviceProfile::default();
        profile.matcher.vendor_id = None;
        assert_eq!(
            render_rc003_keyd_preview(&profile),
            Err(KeydPreviewError::MissingStableDeviceId)
        );

        let mut profile = DeviceProfile::default();
        profile.matcher.product_id = Some(0x0001);
        assert_eq!(
            render_rc003_keyd_preview(&profile),
            Err(KeydPreviewError::UnsupportedDeviceId {
                vendor: 0x2717,
                product: 0x0001,
            })
        );

        let profile = DeviceProfile {
            ptt_key: "F19".into(),
            ..DeviceProfile::default()
        };
        assert_eq!(
            render_rc003_keyd_preview(&profile),
            Err(KeydPreviewError::UnsupportedPttKey("F19".into()))
        );
    }
}
