use crate::config::is_supported_shortcut_key;
use crate::i18n::{Language, language, tr};
use crate::keyd::{RC003_VERIFIED_BUTTON_KEYS, button_id};
use std::error::Error;
use std::fmt;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

const KEYD_DIRECTORY: &str = "/etc/keyd";
const KEYD_PATH: &str = "/usr/bin/keyd";
const TARGET_NAME: &str = "sayall-rc003.conf";
const BACKUP_NAME: &str = "sayall-rc003.conf.sayall-backup";

const HEADER: [&str; 7] = [
    "# Generated by SayAll from the selected device Profile.",
    "# RC003 mappings: validated before atomic installation.",
    "[ids]",
    "k:2717:32b8",
    "",
    "[main]",
    "f5 = f20",
];

const SAFE_BINDINGS: [&str; 14] = [
    "noop",
    "esc",
    "enter",
    "backspace",
    "up",
    "down",
    "left",
    "right",
    "compose",
    "A-tab",
    "volumeup",
    "volumedown",
    "mute",
    "playpause",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApplyOutcome {
    Applied,
    Unchanged,
}

#[derive(Debug)]
pub struct KeydApplyError(String);

impl KeydApplyError {
    fn new(message: impl Into<String>) -> Self {
        Self(message.into())
    }
}

impl fmt::Display for KeydApplyError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for KeydApplyError {}

pub fn validate_rc003_keyd_config(config: &str) -> Result<(), KeydApplyError> {
    if config.contains('\r') {
        return Err(KeydApplyError::new(tr(
            "The keyd configuration contains unsupported carriage-return characters",
            "keyd 配置包含不支持的回车字符",
        )));
    }
    let body = config.strip_suffix('\n').ok_or_else(|| {
        KeydApplyError::new(tr(
            "The keyd configuration must end with a newline",
            "keyd 配置必须以换行结束",
        ))
    })?;
    let lines = body.split('\n').collect::<Vec<_>>();
    let expected_line_count = HEADER.len() + 1 + RC003_VERIFIED_BUTTON_KEYS.len();
    if lines.len() != expected_line_count {
        return Err(KeydApplyError::new(match language() {
            Language::English => format!(
                "Invalid keyd configuration line count: expected {expected_line_count}, found {}",
                lines.len()
            ),
            Language::SimplifiedChinese => format!(
                "keyd 配置行数无效：预期 {expected_line_count}，实际 {}",
                lines.len()
            ),
        }));
    }
    if lines[..HEADER.len()] != HEADER {
        return Err(KeydApplyError::new(tr(
            "Invalid keyd configuration header; only OmaVoice-generated RC003 2717:32b8 configurations are accepted",
            "keyd 配置头无效；只接受 OmaVoice 生成的 RC003 2717:32b8 配置",
        )));
    }
    if lines[HEADER.len()] != "# power unchanged (not captured by keyd)" {
        return Err(KeydApplyError::new(tr(
            "Power must remain unchanged; no other Power action can be applied until it can be captured safely",
            "Power 只能保持原键；安全捕获前不能应用其他 Power 动作",
        )));
    }

    for (offset, (button, source_key)) in RC003_VERIFIED_BUTTON_KEYS.iter().enumerate() {
        let line = lines[HEADER.len() + 1 + offset];
        let unchanged = format!("# {source_key} unchanged ({})", button_id(*button));
        if line == unchanged {
            continue;
        }
        let prefix = format!("{source_key} = ");
        let binding = line.strip_prefix(&prefix).ok_or_else(|| {
            KeydApplyError::new(match language() {
                Language::English => format!(
                    "Invalid keyd source key or generation order for {}",
                    button_id(*button)
                ),
                Language::SimplifiedChinese => {
                    format!("{} 的 keyd 源键或生成顺序无效", button_id(*button))
                }
            })
        })?;
        if !is_safe_binding(binding) {
            return Err(KeydApplyError::new(match language() {
                Language::English => {
                    format!("{} contains a disallowed keyd action", button_id(*button))
                }
                Language::SimplifiedChinese => {
                    format!("{} 包含不允许的 keyd 动作", button_id(*button))
                }
            }));
        }
    }

    Ok(())
}

fn is_safe_binding(binding: &str) -> bool {
    if SAFE_BINDINGS.contains(&binding) {
        return true;
    }

    let mut key = binding;
    for prefix in ["C-", "A-", "S-", "M-"] {
        if let Some(remainder) = key.strip_prefix(prefix) {
            key = remainder;
        }
    }
    !key.contains('-') && is_supported_shortcut_key(key)
}

pub fn apply_rc003_keyd_config(config: &str) -> Result<ApplyOutcome, KeydApplyError> {
    apply_at(config, Path::new(KEYD_DIRECTORY), Path::new(KEYD_PATH))
}

fn apply_at(
    config: &str,
    directory: &Path,
    keyd_path: &Path,
) -> Result<ApplyOutcome, KeydApplyError> {
    validate_rc003_keyd_config(config)?;
    ensure_directory(directory)?;

    let target = directory.join(TARGET_NAME);
    let backup = directory.join(BACKUP_NAME);
    let had_previous =
        ensure_regular_or_missing(&target, tr("Existing keyd configuration", "现有 keyd 配置"))?;
    ensure_regular_or_missing(&backup, tr("keyd backup", "keyd 备份"))?;

    if had_previous && read_file(&target)? == config.as_bytes() {
        return Ok(ApplyOutcome::Unchanged);
    }

    let mut candidate = create_temporary(directory, "sayall-rc003-candidate", 0o644)?;
    candidate.write_all(config.as_bytes())?;
    candidate.sync()?;
    run_keyd(keyd_path, "check", Some(candidate.path()))?;

    if had_previous {
        run_keyd(keyd_path, "check", Some(&target)).map_err(|error| {
            KeydApplyError::new(match language() {
                Language::English => format!("The existing keyd configuration cannot be used as a rollback point; no changes were applied: {error}"),
                Language::SimplifiedChinese => format!("现有 keyd 配置无法作为回滚点，未执行应用：{error}"),
            })
        })?;
        let mut backup_candidate = create_temporary(directory, "sayall-rc003-backup", 0o600)?;
        backup_candidate.write_all(&read_file(&target)?)?;
        backup_candidate.sync()?;
        backup_candidate.persist(&backup)?;
        sync_directory(directory)?;
    } else if backup.exists() {
        fs::remove_file(&backup).map_err(|error| {
            filesystem_error(tr("remove the stale backup", "删除过期备份"), error)
        })?;
        sync_directory(directory)?;
    }

    candidate.persist(&target)?;
    sync_directory(directory)?;

    if let Err(reload_error) = run_keyd(keyd_path, "reload", None) {
        let rollback_result = rollback(directory, keyd_path, &target, &backup, had_previous);
        return match rollback_result {
            Ok(()) => Err(KeydApplyError::new(match language() {
                Language::English => format!(
                    "keyd reload failed; the previous configuration was restored and reloaded: {reload_error}"
                ),
                Language::SimplifiedChinese => {
                    format!("keyd reload 失败，已恢复并重新加载上一份配置：{reload_error}")
                }
            })),
            Err(rollback_error) => Err(KeydApplyError::new(match language() {
                Language::English => format!(
                    "keyd reload failed, and automatic rollback also failed: {reload_error}; {rollback_error}"
                ),
                Language::SimplifiedChinese => {
                    format!("keyd reload 失败，自动回滚也失败：{reload_error}；{rollback_error}")
                }
            })),
        };
    }

    Ok(ApplyOutcome::Applied)
}

fn rollback(
    directory: &Path,
    keyd_path: &Path,
    target: &Path,
    backup: &Path,
    had_previous: bool,
) -> Result<(), KeydApplyError> {
    if had_previous {
        let mut rollback_candidate = create_temporary(directory, "sayall-rc003-rollback", 0o644)?;
        rollback_candidate.write_all(&read_file(backup)?)?;
        rollback_candidate.sync()?;
        rollback_candidate.persist(target)?;
    } else if target.exists() {
        fs::remove_file(target).map_err(|error| {
            filesystem_error(tr("remove the failed configuration", "移除失败配置"), error)
        })?;
    }
    sync_directory(directory)?;
    run_keyd(keyd_path, "reload", None)
}

fn ensure_directory(path: &Path) -> Result<(), KeydApplyError> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| filesystem_error(tr("read /etc/keyd", "读取 /etc/keyd"), error))?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(KeydApplyError::new(tr(
            "The keyd configuration directory is not a safe, real directory",
            "keyd 配置目录不是安全的真实目录",
        )));
    }
    Ok(())
}

fn ensure_regular_or_missing(path: &Path, label: &str) -> Result<bool, KeydApplyError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            Err(KeydApplyError::new(match language() {
                Language::English => format!("{label} is not a safe regular file"),
                Language::SimplifiedChinese => format!("{label}不是安全的普通文件"),
            }))
        }
        Ok(_) => Ok(true),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(filesystem_error_owned(
            match language() {
                Language::English => format!("read {label}"),
                Language::SimplifiedChinese => format!("读取{label}"),
            },
            error,
        )),
    }
}

fn read_file(path: &Path) -> Result<Vec<u8>, KeydApplyError> {
    fs::read(path).map_err(|error| {
        filesystem_error(tr("read the keyd configuration", "读取 keyd 配置"), error)
    })
}

fn sync_directory(path: &Path) -> Result<(), KeydApplyError> {
    File::open(path)
        .and_then(|directory| directory.sync_all())
        .map_err(|error| {
            filesystem_error(
                tr(
                    "sync the keyd configuration directory",
                    "同步 keyd 配置目录",
                ),
                error,
            )
        })
}

fn run_keyd(keyd_path: &Path, command: &str, path: Option<&Path>) -> Result<(), KeydApplyError> {
    let mut process = Command::new(keyd_path);
    process.arg(command);
    if let Some(path) = path {
        process.arg(path);
    }
    let output = process.output().map_err(|error| {
        KeydApplyError::new(match language() {
            Language::English => format!("Could not run keyd {command}: {error}"),
            Language::SimplifiedChinese => format!("无法运行 keyd {command}：{error}"),
        })
    })?;
    if output.status.success() {
        Ok(())
    } else {
        Err(KeydApplyError::new(match language() {
            Language::English => format!("keyd {command} failed: {}", output_message(&output)),
            Language::SimplifiedChinese => {
                format!("keyd {command} 失败：{}", output_message(&output))
            }
        }))
    }
}

fn output_message(output: &Output) -> String {
    let bytes = if output.stderr.is_empty() {
        &output.stdout
    } else {
        &output.stderr
    };
    let message = String::from_utf8_lossy(bytes);
    let trimmed = message.trim();
    if trimmed.is_empty() {
        match language() {
            Language::English => format!("exit status {}", output.status),
            Language::SimplifiedChinese => format!("退出状态 {}", output.status),
        }
    } else {
        trimmed.chars().take(512).collect()
    }
}

fn filesystem_error(operation: &str, error: io::Error) -> KeydApplyError {
    filesystem_error_owned(operation.to_string(), error)
}

fn filesystem_error_owned(operation: String, error: io::Error) -> KeydApplyError {
    KeydApplyError::new(match language() {
        Language::English => format!("Failed to {operation}: {error}"),
        Language::SimplifiedChinese => format!("{operation}失败：{error}"),
    })
}

struct TemporaryConfig {
    path: Option<PathBuf>,
    file: File,
    mode: u32,
}

impl TemporaryConfig {
    fn path(&self) -> &Path {
        self.path.as_deref().expect("temporary path is present")
    }

    fn write_all(&mut self, bytes: &[u8]) -> Result<(), KeydApplyError> {
        self.file.write_all(bytes).map_err(|error| {
            filesystem_error(
                tr(
                    "write the temporary keyd configuration",
                    "写入临时 keyd 配置",
                ),
                error,
            )
        })
    }

    fn sync(&self) -> Result<(), KeydApplyError> {
        self.file.sync_all().map_err(|error| {
            filesystem_error(
                tr(
                    "sync the temporary keyd configuration",
                    "同步临时 keyd 配置",
                ),
                error,
            )
        })
    }

    fn persist(mut self, target: &Path) -> Result<(), KeydApplyError> {
        self.file
            .set_permissions(fs::Permissions::from_mode(self.mode))
            .map_err(|error| {
                filesystem_error(tr("set keyd file permissions", "设置 keyd 文件权限"), error)
            })?;
        let source = self.path.take().expect("temporary path is present");
        match fs::rename(&source, target) {
            Ok(()) => Ok(()),
            Err(error) => {
                self.path = Some(source);
                Err(filesystem_error(
                    tr(
                        "atomically replace the keyd configuration",
                        "原子替换 keyd 配置",
                    ),
                    error,
                ))
            }
        }
    }
}

impl Drop for TemporaryConfig {
    fn drop(&mut self) {
        if let Some(path) = self.path.as_ref() {
            let _ = fs::remove_file(path);
        }
    }
}

fn create_temporary(
    directory: &Path,
    prefix: &str,
    mode: u32,
) -> Result<TemporaryConfig, KeydApplyError> {
    for attempt in 0..100 {
        let path = directory.join(format!(".{prefix}-{}-{attempt}.tmp", std::process::id()));
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(mode)
            .open(&path)
        {
            Ok(file) => {
                return Ok(TemporaryConfig {
                    path: Some(path),
                    file,
                    mode,
                });
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(filesystem_error(
                    tr(
                        "create a temporary keyd configuration",
                        "创建临时 keyd 配置",
                    ),
                    error,
                ));
            }
        }
    }
    Err(KeydApplyError::new(tr(
        "Could not create a unique temporary keyd configuration",
        "无法创建唯一的临时 keyd 配置",
    )))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ButtonAction, DeviceProfile, KeyboardShortcut, RemoteButton};
    use crate::keyd::render_rc003_keyd_preview;
    use std::os::unix::fs::PermissionsExt;
    use tempfile::TempDir;

    fn ready_config() -> String {
        let mut profile = DeviceProfile::default();
        profile
            .button_mappings
            .insert(RemoteButton::Power, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Home, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Back, ButtonAction::Escape);
        profile
            .button_mappings
            .insert(RemoteButton::Tv, ButtonAction::Backspace);
        let preview = render_rc003_keyd_preview(&profile).unwrap();
        assert!(preview.ready_to_apply());
        preview.config
    }

    fn fake_keyd(directory: &Path) -> PathBuf {
        let path = directory.join("keyd");
        let script = r#"#!/bin/sh
base=$(dirname -- "$0")
printf '%s\n' "$*" >> "$base/keyd.log"
if [ "$1" = check ] && [ -e "$base/fail-check" ]; then
  echo 'simulated check failure' >&2
  exit 1
fi
if [ "$1" = reload ] && [ -e "$base/fail-reload-once" ] && [ ! -e "$base/reload-failed" ]; then
  : > "$base/reload-failed"
  echo 'simulated reload failure' >&2
  exit 1
fi
exit 0
"#;
        fs::write(&path, script).unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
        path
    }

    #[test]
    fn validator_accepts_only_generated_fixed_rc003_shape() {
        let config = ready_config();
        validate_rc003_keyd_config(&config).unwrap();

        for invalid in [
            config.replace("k:2717:32b8", "*"),
            config.replace("back = esc", "back = command(evil)"),
            config.replace("compose = compose", "compose = menu"),
            config.replace("# power unchanged (not captured by keyd)", "power = esc"),
            format!("{config}[extra]\nfoo = bar\n"),
            config.trim_end().to_string(),
        ] {
            assert!(validate_rc003_keyd_config(&invalid).is_err());
        }
    }

    #[test]
    fn validator_accepts_structured_shortcuts_and_rejects_keyd_language_injection() {
        let mut profile = DeviceProfile::default();
        profile
            .button_mappings
            .insert(RemoteButton::Power, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Home, ButtonAction::PassThrough);
        profile
            .button_mappings
            .insert(RemoteButton::Tv, ButtonAction::CustomShortcut);
        profile.button_shortcuts.insert(
            RemoteButton::Tv,
            KeyboardShortcut::from_input(true, true, false, true, "delete").unwrap(),
        );
        let config = render_rc003_keyd_preview(&profile).unwrap().config;

        validate_rc003_keyd_config(&config).unwrap();
        assert!(config.contains("grave = C-A-M-delete"));
        for invalid in [
            config.replace("C-A-M-delete", "macro(C-t enter)"),
            config.replace("C-A-M-delete", "command(evil)"),
            config.replace("C-A-M-delete", "M-A-delete"),
            config.replace("C-A-M-delete", "C-C-delete"),
            config.replace("C-A-M-delete", "f20"),
        ] {
            assert!(validate_rc003_keyd_config(&invalid).is_err());
        }
    }

    #[test]
    fn apply_checks_backs_up_and_atomically_replaces_config() {
        let temporary = TempDir::new().unwrap();
        let directory = temporary.path();
        let keyd = fake_keyd(directory);
        let target = directory.join(TARGET_NAME);
        fs::write(&target, "old valid config").unwrap();
        let config = ready_config();

        assert_eq!(
            apply_at(&config, directory, &keyd).unwrap(),
            ApplyOutcome::Applied
        );

        assert_eq!(fs::read_to_string(&target).unwrap(), config);
        assert_eq!(
            fs::read_to_string(directory.join(BACKUP_NAME)).unwrap(),
            "old valid config"
        );
        assert_eq!(
            fs::metadata(&target).unwrap().permissions().mode() & 0o777,
            0o644
        );
        assert_eq!(
            fs::metadata(directory.join(BACKUP_NAME))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        let log = fs::read_to_string(directory.join("keyd.log")).unwrap();
        assert_eq!(log.lines().filter(|line| *line == "reload").count(), 1);
        assert!(!fs::read_dir(directory).unwrap().any(|entry| {
            entry
                .unwrap()
                .file_name()
                .to_string_lossy()
                .ends_with(".tmp")
        }));
    }

    #[test]
    fn check_failure_preserves_previous_config() {
        let temporary = TempDir::new().unwrap();
        let directory = temporary.path();
        let keyd = fake_keyd(directory);
        let target = directory.join(TARGET_NAME);
        fs::write(&target, "old valid config").unwrap();
        fs::write(directory.join("fail-check"), "").unwrap();

        assert!(apply_at(&ready_config(), directory, &keyd).is_err());
        assert_eq!(fs::read_to_string(target).unwrap(), "old valid config");
        assert!(!directory.join(BACKUP_NAME).exists());
    }

    #[test]
    fn reload_failure_restores_and_reloads_previous_config() {
        let temporary = TempDir::new().unwrap();
        let directory = temporary.path();
        let keyd = fake_keyd(directory);
        let target = directory.join(TARGET_NAME);
        fs::write(&target, "old valid config").unwrap();
        fs::write(directory.join("fail-reload-once"), "").unwrap();

        let error = apply_at(&ready_config(), directory, &keyd)
            .unwrap_err()
            .to_string();

        assert!(error.contains(tr(
            "the previous configuration was restored and reloaded",
            "已恢复并重新加载上一份配置"
        )));
        assert_eq!(fs::read_to_string(target).unwrap(), "old valid config");
        let log = fs::read_to_string(directory.join("keyd.log")).unwrap();
        assert_eq!(log.lines().filter(|line| *line == "reload").count(), 2);
    }

    #[test]
    fn unchanged_config_does_not_reload_or_replace_backup() {
        let temporary = TempDir::new().unwrap();
        let directory = temporary.path();
        let keyd = fake_keyd(directory);
        let target = directory.join(TARGET_NAME);
        let backup = directory.join(BACKUP_NAME);
        let config = ready_config();
        fs::write(&target, &config).unwrap();
        fs::write(&backup, "existing backup").unwrap();

        assert_eq!(
            apply_at(&config, directory, &keyd).unwrap(),
            ApplyOutcome::Unchanged
        );
        assert_eq!(fs::read_to_string(backup).unwrap(), "existing backup");
        assert!(!directory.join("keyd.log").exists());
    }

    #[test]
    fn symlink_target_is_rejected_without_running_keyd() {
        let temporary = TempDir::new().unwrap();
        let directory = temporary.path();
        let keyd = fake_keyd(directory);
        std::os::unix::fs::symlink("elsewhere", directory.join(TARGET_NAME)).unwrap();

        assert!(apply_at(&ready_config(), directory, &keyd).is_err());
        assert!(!directory.join("keyd.log").exists());
    }
}
